remote_theme: resume-template
show_downloads: false
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: José Rogelio Ruiz Martínez
description: Estudiante de Ingeniería en Robótica y Sistemas Digitales
